[package]
name = "deadlock-webhook"
version = "2.1.0"
edition = "2024"

[dependencies]
serenity = "0.12.5"
tokio = { version = "1.53.2", features = ["macros", "rt"] }
color-eyre = "0.6.5"
steam-rs = { git = "https://github.com/justdeeevin/steam-rs", branch = "backport-fix-feeds-param" }
clap = { version = "4.6.6", features = ["derive"] }
regex = "1.13.1"
aho-corasick = "1.1.5"
